### ISSUE TITLE
Wildfire test code doesn't run

### ISSUE THREAD

**Issue by miki-yuasa** [Tran-Research-Group/gym-multigrid#140]
@npnike10 I can't run the test code due to the following error. Can you fix this?

```
___________________ ERROR collecting tests/test_wildfire.py ____________________
tests/test_wildfire.py:51: in <module>
    test_wildfire()
tests/test_wildfire.py:34: in test_wildfire
    obs, _ = env.reset()
../../.cache/pypoetry/virtualenvs/gym-multigrid-qmFzXpDy-py3.10/lib/python3.10/site-packages/gymnasium/wrappers/common.py:146: in reset
    return super().reset(seed=seed, options=options)
../../.cache/pypoetry/virtualenvs/gym-multigrid-qmFzXpDy-py3.10/lib/python3.10/site-packages/gymnasium/core.py:328: in reset
    return self.env.reset(seed=seed, options=options)
../../.cache/pypoetry/virtualenvs/gym-multigrid-qmFzXpDy-py3.10/lib/python3.10/site-packages/gymnasium/wrappers/common.py:400: in reset
    return super().reset(seed=seed, options=options)
../../.cache/pypoetry/virtualenvs/gym-multigrid-qmFzXpDy-py3.10/lib/python3.10/site-packages/gymnasium/core.py:328: in reset
    return self.env.reset(seed=seed, options=options)
../../.cache/pypoetry/virtualenvs/gym-multigrid-qmFzXpDy-py3.10/lib/python3.10/site-packages/gymnasium/wrappers/common.py:293: in reset
    return env_reset_passive_checker(self.env, seed=seed, options=options)
../../.cache/pypoetry/virtualenvs/gym-multigrid-qmFzXpDy-py3.10/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py:185: in env_reset_passive_checker
    result = env.reset(**kwargs)
gym_multigrid/envs/wildfire.py:637: in reset
    state = options["state"]
E   TypeError: 'NoneType' object is not subscriptable
```

**Comment by npnike10** [comment]
The test runs fine for me when I run the file from terminal. But testing in VS code seems to raise an error so I've pushed a commit, implementing the change in options arg of reset in wildfire.py, as we discussed. Could you let me know if it's fine now?

**Comment by miki-yuasa** [comment]
@npnike10  Can you tell me which branch you pushed the change?

**Comment by npnike10** [comment]
Yea it’s commit a859769 in dev branch.

**Comment by miki-yuasa** [comment]
It still shows a bug:
```
tests/test_wildfire.py:42: in test_wildfire
    f"{a.index}": np.random.choice(list(env.actions)) for a in env.agents
E   AttributeError: 'TimeLimit' object has no attribute 'agents'
```

Can you create a branch `fix/140-wf-test` and work on this?

**Comment by jaye-heglund** [comment]
@miki-yuasa @npnike10 
I ended up fixing this when I was getting pytest working on the `dev-subtasks` branch. The `fix/140-wf-test` branch can be deleted if there are not any other changes on that branch, since my changes have already been merged into the `dev` branch.

The issue here is that Gymnasium automatically applies wrappers to the environment when you call `make`, and the `agents` property is not something you can call in the standard Gymnasium API, so is not available outside the env class after the wrappers are applied. You can get the env's agents by calling `env.unwrapped.agents`, which is a useful way of showing when we break the Gymnasium API for the sake of convenience.

This issue can be closed.

**Comment by npnike10** [comment]
That makes sense, thank you for fixing!

**Comment by miki-yuasa** [comment]
Thank you @jacob-heglund  for fixing this! Closing by #148
